-- Create table for Daily Professor Lock Insights
CREATE TABLE IF NOT EXISTS daily_professor_insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'research',
    confidence INTEGER DEFAULT 75 CHECK (confidence >= 0 AND confidence <= 100),
    impact TEXT DEFAULT 'medium' CHECK (impact IN ('low', 'medium', 'high')),
    research_sources TEXT[] DEFAULT '{}',
    game_info JSONB DEFAULT NULL,
    teams TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_daily_professor_insights_created_at ON daily_professor_insights(created_at);
CREATE INDEX IF NOT EXISTS idx_daily_professor_insights_category ON daily_professor_insights(category);
CREATE INDEX IF NOT EXISTS idx_daily_professor_insights_impact ON daily_professor_insights(impact);

-- Create trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_daily_professor_insights_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_daily_professor_insights_updated_at
    BEFORE UPDATE ON daily_professor_insights
    FOR EACH ROW
    EXECUTE FUNCTION update_daily_professor_insights_updated_at();

-- Enable RLS (Row Level Security)
ALTER TABLE daily_professor_insights ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all authenticated users to read insights
CREATE POLICY "Anyone can read daily professor insights"
    ON daily_professor_insights
    FOR SELECT
    TO authenticated
    USING (true);

-- Create policy to allow service role to insert/update insights
CREATE POLICY "Service role can manage daily professor insights"
    ON daily_professor_insights
    FOR ALL
    TO service_role
    USING (true);

-- Grant permissions
GRANT SELECT ON daily_professor_insights TO authenticated;
GRANT ALL ON daily_professor_insights TO service_role;

-- Add comment for documentation
COMMENT ON TABLE daily_professor_insights IS 'Stores daily research insights generated by Professor Lock AI for Pro users';

-- Add column comments
COMMENT ON COLUMN daily_professor_insights.title IS 'Insight title/headline';
COMMENT ON COLUMN daily_professor_insights.description IS 'Detailed insight description';
COMMENT ON COLUMN daily_professor_insights.category IS 'Type of insight: weather, injury, pitcher, bullpen, trends, matchup, research';
COMMENT ON COLUMN daily_professor_insights.confidence IS 'Confidence score 0-100';
COMMENT ON COLUMN daily_professor_insights.impact IS 'Impact level: low, medium, high';
COMMENT ON COLUMN daily_professor_insights.research_sources IS 'Array of data sources used for research';
COMMENT ON COLUMN daily_professor_insights.game_info IS 'JSON with game details if insight is game-specific';
COMMENT ON COLUMN daily_professor_insights.teams IS 'Array of team names mentioned in insight'; 