[build]
builder = "nixpacks"

[deploy]  
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"

[nixpacks]
provider = "node"
installPhase = "cd backend && npm install"
startCommand = "cd backend && npm start"
