[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn statmuse_api_server:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"

[nixpacks]
aptPkgs = ["python3", "python3-pip"]
installPhase = "pip install -r statmuse-requirements.txt"
