[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'cd python-services/sports-betting-api && gunicorn ml_prediction_server:app --bind 0.0.0.0:$PORT'"
healthcheckPath = "/health"

[nixpacks]
aptPkgs = ["python3", "python3-pip", "bash"]
installPhase = "pip install -r ml-requirements.txt"
