[build]
builder = "nixpacks"

[deploy]  
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"

[nixpacks]
aptPkgs = ["nodejs", "npm"]
installPhase = "npm install --prefix backend"
buildPhase = "npm run build:babel --prefix backend"
