[build]
builder = "nixpacks"

[deploy]  
startCommand = "sh -c 'cd backend && npm start'"
healthcheckPath = "/api/health"

[nixpacks]
aptPkgs = ["nodejs", "npm", "bash"]
installPhase = "npm install --prefix backend"
buildPhase = "npm run build:babel --prefix backend"
