[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[[services]]
name = "backend"
[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
[services.deploy]
startCommand = "node /app/backend/dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[[services]]
name = "ml"
[services.build]
builder = "nixpacks"
[services.build.nixpacks]
installPhase = "pip install -r ml-requirements.txt"
aptPkgs = ["python3", "python3-pip", "bash"]
[services.deploy]
startCommand = "sh -c 'cd python-services/sports-betting-api && gunicorn ml_prediction_server:app --bind 0.0.0.0:$PORT'"
healthcheckPath = "/health"

[[services]]
name = "statmuse"
[services.build]
builder = "nixpacks"
[services.build.nixpacks]
installPhase = "pip install -r statmuse-requirements.txt"
aptPkgs = ["python3", "python3-pip"]
[services.deploy]
startCommand = "gunicorn statmuse_api_server:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"