[build]
builder = "nixpacks"

[deploy]  
startCommand = "cd backend && npm start"
healthcheckPath = "/api/health"

[nixpacks]
aptPkgs = ["nodejs", "npm"]
installPhase = "cd backend && npm install"
buildPhase = "cd backend && npm run build:babel"
