[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[[services]]
name = "backend"
[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
[services.deploy]
startCommand = "node /app/apps/backend/dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[[services]]
name = "orchestrator"
[services.build]
builder = "nixpacks"
[services.build.nixpacks]
installPhase = "pip install -r ml-requirements.txt"
aptPkgs = ["python3", "python3-pip", "bash", "curl"]
[services.deploy]
startCommand = "python main.py --mode both --test"
healthcheckPath = ""

[[services]]
name = "statmuse"
[services.build]
builder = "nixpacks"
[services.build.nixpacks]
installPhase = "pip install -r statmuse-requirements.txt"
aptPkgs = ["python3", "python3-pip"]
[services.deploy]
startCommand = "gunicorn statmuse_api_server:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"