# Railway Production Configuration for Professor Lock Agent
# This file will be copied to config/config.toml during Railway build

[llm]
model = "gpt-4o"
base_url = "https://api.openai.com/v1"
api_key = "${OPENAI_API_KEY}"
max_tokens = 15000
temperature = 0.0

[llm.vision]
model = "claude-3-7-sonnet-20250219"
base_url = "https://api.anthropic.com/v1/"
api_key = "${ANTHROPIC_API_KEY}"
max_tokens = 8192
temperature = 0.0

# Daytona configuration for isolated sandboxes
[daytona]
daytona_api_key = "${DAYTONA_API_KEY}"
daytona_server_url = "https://app.daytona.io/api"
daytona_target = "us"
sandbox_image_name = "whitezxj/sandbox:0.1.0"
sandbox_entrypoint = "/usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf"
VNC_password = "123456"

[mcp]
server_reference = "app.mcp.server"

[runflow]
use_data_analysis_agent = false
